# Generated by Django 5.2.17 on 2026-08-09 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('delivery', '0002_deliveryassignment_driver_latitude_and_more'),
        ('orders', '0002_alter_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eta_minutes', models.PositiveIntegerField(default=30)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_bids', to='orders.order')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='accounts.deliverypartnerprofile')),
            ],
            options={
                'db_table': 'delivery_bids',
                'ordering': ['amount', 'created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='delivery_bi_order_i_152d5a_idx')],
                'unique_together': {('order', 'partner')},
            },
        ),
    ]
