# Generated by Django 5.2.14 on 2026-05-17 16:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/')),
                ('latitude', models.DecimalField(decimal_places=6, default=28.6139, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=77.209, max_digits=9)),
                ('delivery_time_min', models.PositiveIntegerField(default=15)),
                ('delivery_time_max', models.PositiveIntegerField(default=25)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.vendorprofile')),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='StoreHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='stores.store')),
            ],
            options={
                'db_table': 'store_hours',
                'unique_together': {('store', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='StoreStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_manage_inventory', models.BooleanField(default=True)),
                ('can_manage_orders', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_staff',
                'unique_together': {('user', 'store')},
            },
        ),
    ]
